title: Zach's Compass
description: Tech and life, one post at a time.
url: "https://zachc-ai.github.io"
baseurl: ""

theme: minima

permalink: /blog/:title/

header_pages:
  - blog.md
  - digests.md
  - tags.md
  - about.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

author: ZachC

giscus:
  repo: "zachc-ai/zachc-ai.github.io"
  repo_id: "R_kgDORoQKJg"
  category: "Announcements"
  category_id: "DIC_kwDORoQKJs4C4jVh"
